version = 0.1
[default.deploy.parameters]
stack_name = "finance-doc-auth-services"
resolve_s3 = true
s3_prefix = "finance-doc-auth-services"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"finance-doc-auth-services\""
image_repositories = []
