version = 0.1
[default.deploy.parameters]
stack_name = "web-api-local"
resolve_s3 = true
s3_prefix = "web-api-local"
region = "us-west-2"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
parameter_overrides = "ProjectName=\"web-api-local\""
image_repositories = []
