AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Web Api

Parameters:
  ProjectName:
    Type: String
    Default: web-api

Resources:
  ApiGatewayExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-ApiGatewayExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ProjectName}-S3AccessPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: !Sub
                  - "arn:aws:s3:::${InputBucket}/*"
                  - InputBucket: !ImportValue finance-doc-core-infra-input-bucket

  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${ProjectName}"
      RetentionInDays: 3

  WebApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${ProjectName}"
      BinaryMediaTypes:
        - application/pdf

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  V1Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref WebApi
      ParentId: !GetAtt WebApi.RootResourceId
      PathPart: v1

  DocumentsEndpoint:
    Type: AWS::Serverless::Application
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        ApiGatewayExecutionRoleArn: !GetAtt ApiGatewayExecutionRole.Arn
        WebApi: !Ref WebApi
        V1Resource: !Ref V1Resource
      Location: ./v1/documents/template.yaml

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - DocumentsEndpoint
    Properties:
      RestApiId: !Ref WebApi
      Description: "Initial deployment of web-api"

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref WebApi
      DeploymentId: !Ref ApiDeployment
      StageName: dev
      Description: Stage for web-api
      Variables:
        inputBucket: !ImportValue finance-doc-core-infra-input-bucket
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: '{"requestId": "$context.requestId", "requestTime": "$context.requestTime", "httpMethod": "$context.httpMethod", "resourcePath": "$context.resourcePath", "status": "$context.status", "error.message": "$context.error.message", "error.messageString": "$context.error.messageString"}'

  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "${ProjectName}-usage-plan"
      Description: "Usage plan for web-api"
      ApiStages:
        - ApiId: !Ref WebApi
          Stage: !Ref ApiStage
      Throttle:
        RateLimit: 10
        BurstLimit: 20
      Quota:
        Limit: 50
        Period: DAY

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${ProjectName}-key"
      Description: "API key for web-api access"
      Enabled: true

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan

Outputs:
  ApiUrl:
    Description: "URL of the API Gateway"
    Value: !Sub "https://${WebApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
    Export:
      Name: !Sub "${ProjectName}-api-url"
  
  ApiId:
    Description: "ID of the API Gateway"
    Value: !Ref WebApi
    Export:
      Name: !Sub "${ProjectName}-api-id"

  ApiKeyId:
    Description: "ID of the API Key"
    Value: !Ref ApiKey
    Export:
      Name: !Sub "${ProjectName}-api-key-id"
