version = 0.1
[default.deploy.parameters]
stack_name = "doc-reader-local"
resolve_s3 = true
s3_prefix = "doc-reader-local"
region = "us-west-2"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = "ProjectName=\"doc-reader-local\""
image_repositories = []
