AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploys the necessary infrastructure for the doc-reader container,
  enabling it to be run as a Fargate task orchestrated by Step Functions.

Parameters:
  ProjectName:
    Type: String
    Default: doc-reader

Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-TaskRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ProjectName}-S3AccessPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub 
                  - "arn:aws:s3:::${InputBucket}"
                  - InputBucket: !ImportValue finance-doc-core-infra-input-bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub
                  - "arn:aws:s3:::${InputBucket}/*"
                  - InputBucket: !ImportValue finance-doc-core-infra-input-bucket
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub
                  - "arn:aws:s3:::${OutputBucket}/*"
                  - OutputBucket: !ImportValue finance-doc-core-infra-output-bucket

  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE

  # Role for ECS agent to pull image and write logs
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-TaskExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ProjectName}"
      RetentionInDays: 30

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ProjectName
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: "4096" # 4 vCPU
      Memory: "16384" # 16 GB - Marker can be memory intensive
      RuntimePlatform:
        CpuArchitecture: ARM64
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: !Ref ProjectName
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}:latest"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          # Environment variables are provided at runtime by the Step Function
          # The entrypoint.sh script expects INPUT_S3_URI and OUTPUT_S3_URI_PREFIX
          Environment: []

  DocReaderEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: doc-reader
      Description: "Custom event bus for doc-reader service events"
      Tags:
        - Key: Service
          Value: doc-reader
        - Key: Purpose
          Value: event-driven-processing

Outputs:
  EcrRepositoryUri:
    Description: "The URI of the ECR repository for the doc-reader image"
    Value: !GetAtt EcrRepository.RepositoryUri
  TaskDefinitionArn:
    Description: "The ARN of the ECS Task Definition"
    Value: !Ref TaskDefinition
  DocReaderEventBusName:
    Description: "The name of the custom event bus for doc-reader events"
    Value: !Ref DocReaderEventBus
    Export:
      Name: doc-reader-event-bus-name
  DocReaderEventBusArn:
    Description: "The ARN of the custom event bus for doc-reader events"
    Value: !GetAtt DocReaderEventBus.Arn
    Export:
      Name: doc-reader-event-bus-arn
