AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploys the core infrastructure for the finance-doc-reader

Parameters:
  ProjectName:
    Type: String
    Default: finance-doc-core-infra
  DatabaseName:
    Type: String
    Default: finance_docs
    Description: Name of the PostgreSQL database
  MinCapacity:
    Type: Number
    Default: 0.5
    Description: Minimum Aurora Serverless v2 capacity units
    MinValue: 0.5
    MaxValue: 128
  MaxCapacity:
    Type: Number
    Default: 2.0
    Description: Maximum Aurora Serverless v2 capacity units
    MinValue: 0.5
    MaxValue: 128 

Resources:
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-input-bucket-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-output-bucket-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ProjectName}-cluster"
  
  DocReaderEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: doc-reader
      Description: "Custom event bus for doc-reader service events"

  # Aurora Serverless v2 PostgreSQL Cluster
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub "${ProjectName}-postgres-cluster"
      Engine: aurora-postgresql
      EngineVersion: 16.6
      DatabaseName: !Ref DatabaseName
      MasterUsername: finance_docs
      ManageMasterUserPassword: true
      EnableHttpEndpoint: true
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 16
      BackupRetentionPeriod: 1
      DeletionProtection: false
      PreferredBackupWindow: "03:00-04:00"
      PreferredMaintenanceWindow: "sun:04:00-sun:05:00"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-postgres-cluster"

  # Aurora Serverless v2 Database Instance
  AuroraInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${ProjectName}-postgres-instance"
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-postgres-instance"

Outputs:
  EcsClusterName:
    Description: "The name of the ECS Cluster"
    Value: !Ref EcsCluster
    Export:
      Name: !Sub '${ProjectName}-ecs-cluster'
  InputBucketName:
    Description: "Name of the S3 bucket for input files"
    Value: !Ref InputBucket
    Export:
      Name: !Sub '${ProjectName}-input-bucket'
  OutputBucketName:
    Description: "Name of the S3 bucket for output files"
    Value: !Ref InputBucket
    Export:
      Name: !Sub '${ProjectName}-output-bucket'
  DocReaderEventBusName:
    Description: "Name of the Doc Reader event bus"
    Value: !Ref DocReaderEventBus
    Export:
      Name: !Sub '${ProjectName}-doc-reader-event-bus-name'
  
  AuroraClusterArn:
    Description: "ARN of the Aurora PostgreSQL cluster for Data API access"
    Value: !Sub "arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${AuroraCluster}"
    Export:
      Name: !Sub '${ProjectName}-aurora-cluster-arn'
      
  AuroraClusterEndpoint:
    Description: "Aurora cluster endpoint"
    Value: !GetAtt AuroraCluster.Endpoint.Address
    Export:
      Name: !Sub '${ProjectName}-aurora-cluster-endpoint'
      
  DatabaseSecretArn:
    Description: "ARN of the database master user secret"
    Value: !GetAtt AuroraCluster.MasterUserSecret.SecretArn
    Export:
      Name: !Sub '${ProjectName}-database-secret-arn'
      
  DatabaseName:
    Description: "Name of the PostgreSQL database"
    Value: !Ref DatabaseName
    Export:
      Name: !Sub '${ProjectName}-database-name'
