services:
  doc-reader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./inputs:/inputs
      - ./outputs:/outputs
    environment:
      - INPUT_S3_BUCKET=local-test-bucket
      - OUTPUT_S3_URI_PREFIX=s3://local-test-output
    stdin_open: true  # equivalent to -i
    tty: true        # equivalent to -t
