version = 0.1
[default.deploy.parameters]
stack_name = "llm-processor-local"
resolve_s3 = true
s3_prefix = "llm-processor-local"
region = "us-west-2"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = "ProjectName=\"llm-processor-local\" BedrockModelId=\"anthropic.claude-3-sonnet-20240229-v1:0\""
image_repositories = []
